import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, FileClock, Search, ShieldAlert, Users } from "lucide-react";
import OperationsShell from "@/components/OperationsShell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";

type Period = "today" | "7d" | "30d" | "90d" | "all";
type Category = "workflow" | "incident" | "configuration" | "access" | "history" | "data";
type Status = "success" | "failure";
type AuditEvent = Record<string, any>;
const categories: Record<Category, string> = { workflow: "Workflows", incident: "Incidentes", configuration: "Configurações", access: "Acessos", history: "Histórico", data: "Consultas técnicas" };
const actions: Record<string, string> = { "workflow.toggle": "Status do workflow alterado", "workflow.node_update": "Node editado", "workflow.restore": "Versão restaurada", "incident.update": "Incidente atualizado", "slo.save": "Meta operacional atualizada", "runbook.save": "Plano de resposta atualizado", "alert_rule.save": "Regra de alerta atualizada", "user.save": "Acesso criado ou atualizado", "user.status": "Status de acesso alterado", "user.delete": "Acesso removido", "history.sync": "Histórico sincronizado", "history.details_preserve": "Detalhes preservados", "execution.details_view": "Detalhes técnicos consultados" };
const formatDate = (value: unknown) => { const date = new Date(String(value || "")); return Number.isNaN(date.getTime()) ? "Data indisponível" : date.toLocaleString("pt-BR"); };
function JsonBlock({ title, value }: { title: string; value: unknown }) { if (value == null || (typeof value === "object" && !Object.keys(value as object).length)) return null; return <div><p className="mb-2 text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">{title}</p><pre className="max-h-60 overflow-auto rounded-xl bg-muted/70 p-4 text-xs leading-5">{JSON.stringify(value, null, 2)}</pre></div>; }

export default function Audit() {
  const [period, setPeriod] = useState<Period>("30d"), [category, setCategory] = useState<Category | "all">("all"), [status, setStatus] = useState<Status | "all">("all"), [search, setSearch] = useState(""), [selected, setSelected] = useState<AuditEvent | null>(null);
  const query = trpc.audit.list.useQuery({ period, category: category === "all" ? undefined : category, status: status === "all" ? undefined : status }, { retry: false });
  const events = useMemo(() => {
    const term = search.trim().toLowerCase();
    const rows = (query.data ?? []) as AuditEvent[];
    return term ? rows.filter((item) => [item.actor, item.summary, item.targetName, item.targetId, item.action].some((value) => String(value || "").toLowerCase().includes(term))) : rows;
  }, [query.data, search]);
  const totals = useMemo(() => ({ failures: events.filter((item) => item.status === "failure").length, actors: new Set(events.map((item) => item.actor)).size }), [events]);
  return <OperationsShell><main className="mx-auto max-w-[1320px] px-5 py-8 md:px-9">
    <p className="text-[11px] font-bold uppercase tracking-[.18em] text-muted-foreground">Gestão / Auditoria</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Trilha de auditoria</h1><p className="mt-2 text-sm text-muted-foreground">Acompanhe alterações administrativas, responsáveis e resultados em um único lugar.</p>
    <section className="mt-7 grid gap-4 sm:grid-cols-3">
      {[{ label: "Eventos encontrados", value: events.length, Icon: FileClock }, { label: "Pessoas envolvidas", value: totals.actors, Icon: Users }, { label: "Ações com falha", value: totals.failures, Icon: ShieldAlert }].map(({ label, value, Icon }) => <Card key={label}><CardContent className="flex items-center gap-4 p-5"><Icon className="h-5 w-5 text-primary"/><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div></CardContent></Card>)}
    </section>
    <Card className="mt-5 overflow-hidden"><CardContent className="p-0">
      <div className="grid gap-3 border-b p-5 lg:grid-cols-[1fr_170px_190px_170px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={(event) => setSearch(event.target.value)} className="pl-9" placeholder="Buscar pessoa, ação ou item"/></div>
        <Select value={category} onValueChange={(value) => setCategory(value as Category | "all")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas as áreas</SelectItem>{Object.entries(categories).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>
        <Select value={status} onValueChange={(value) => setStatus(value as Status | "all")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os resultados</SelectItem><SelectItem value="success">Concluídas</SelectItem><SelectItem value="failure">Com falha</SelectItem></SelectContent></Select>
        <Select value={period} onValueChange={(value) => setPeriod(value as Period)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="today">Hoje</SelectItem><SelectItem value="7d">Últimos 7 dias</SelectItem><SelectItem value="30d">Últimos 30 dias</SelectItem><SelectItem value="90d">Últimos 90 dias</SelectItem><SelectItem value="all">Todo o histórico</SelectItem></SelectContent></Select></div>
      <div className="hidden grid-cols-[180px_1.3fr_1fr_160px_120px] gap-4 border-b px-6 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-muted-foreground md:grid"><span>Data</span><span>Ação</span><span>Responsável</span><span>Área</span><span>Resultado</span></div>
      <div className="divide-y">{events.map((event) => <button key={event.id} type="button" onClick={() => setSelected(event)} className="grid w-full gap-2 px-6 py-4 text-left hover:bg-muted/45 md:grid-cols-[180px_1.3fr_1fr_160px_120px] md:items-center md:gap-4"><span className="flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5"/>{formatDate(event.createdAt)}</span><span><span className="block text-sm font-semibold">{actions[event.action] || event.action}</span><span className="mt-1 block text-xs text-muted-foreground">{event.summary}</span></span><span className="truncate text-sm">{event.actor}</span><span className="text-sm text-muted-foreground">{categories[event.category as Category] || event.category}</span><Badge variant="outline" className={event.status === "failure" ? "w-fit border-red-200 bg-red-50 text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300" : "w-fit border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-300"}>{event.status === "failure" ? "Falhou" : "Concluída"}</Badge></button>)}</div>
      {query.isLoading && <div className="p-12 text-center text-sm text-muted-foreground">Carregando a trilha de auditoria…</div>}{!query.isLoading && !query.isError && !events.length && <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 text-sm font-medium">Nenhum evento encontrado</p><p className="mt-1 text-xs text-muted-foreground">Novas ações administrativas aparecerão aqui automaticamente.</p></div>}{query.isError && <div className="p-8 text-center text-sm text-red-600">Não foi possível carregar a auditoria.</div>}
    </CardContent></Card>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{selected ? actions[selected.action] || selected.action : "Detalhes"}</DialogTitle><DialogDescription>{selected?.summary}</DialogDescription></DialogHeader>{selected && <div className="space-y-5"><div className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Responsável</p><p className="mt-1 text-sm font-medium">{selected.actor}</p></div><div><p className="text-xs text-muted-foreground">Data e hora</p><p className="mt-1 text-sm font-medium">{formatDate(selected.createdAt)}</p></div><div><p className="text-xs text-muted-foreground">Item afetado</p><p className="mt-1 text-sm font-medium">{selected.targetName || selected.targetId || selected.targetType}</p></div><div><p className="text-xs text-muted-foreground">Resultado</p><p className="mt-1 text-sm font-medium">{selected.status === "failure" ? "Falhou" : "Concluída"}</p></div></div>{selected.reason && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{selected.reason}</div>}<JsonBlock title="Antes" value={selected.before}/><JsonBlock title="Depois" value={selected.after}/><JsonBlock title="Informações adicionais" value={selected.metadata}/></div>}</DialogContent></Dialog>
  </main></OperationsShell>;
}
